Initial parts of reputation system
ConsenSys/fc-retrieval-gateway pull request #5
Opened 2020-11-27 04:37 UTC by drinkcoffee

First parts of the reputation system. Uses in-memory storage.

Signed-off-by: Peter  Robinson <drinkcoffee@eml.cc>

2020-11-27 04:40 UTC, drinkcoffee commented
it only uses in-memory objects within the package. I figure that we first need to understand what needs to be stored before we get too far into working out how to persist it. I have however separated out the storing / retrieving of data from the data store from the application logic. Also, given there will be a large set of constants, I have them in a separate file. No tests yet.

2020-11-27 05:06 UTC, wcgcyx commented on internal/reputation/reputation_store.go
> +	val, exists = r.clients[clientNodeID.ToString()]
Possibly missing mutex.RLock() ?

2020-11-27 05:17 UTC, wcgcyx requested changes
Possibly missing mutex.RLock() when reading from the client reputation map.

2020-11-27 06:12 UTC, drinkcoffee commented on internal/reputation/reputation_store.go
> +	val, exists = r.clients[clientNodeID.ToString()]
correct. I will fix this.

2020-11-27 06:16 UTC, drinkcoffee commented on internal/reputation/reputation_store.go
> +	val, exists = r.clients[clientNodeID.ToString()]
fixed. Added mutex around all reads

2020-11-27 23:17 UTC, drinkcoffee commented on internal/reputation/reputation_store.go
> +	r.clients[clientNodeIDStr] = val + amount
Have a two constants: maxClientReputation and minClientReputation. Add check & limit (val + amount) to stay within the min and max reputation.

2020-11-29 23:28 UTC, wcgcyx commented on internal/reputation/reputation_store.go
> +	r.clientsMapLock.Lock()
For read operation, maybe we can use RLock()? map should be safe for concurrent read.

2020-11-30 00:24 UTC, merged